### PR TITLE
add mobile device support

### LINKED ISSUE #52: It would be even better if this mod works on mobile phone
Now bpmnjs supports the touch event on the mobile side, but the small map does not support it

I checked the code, the minimap only listens to the mousemove event, it may be a good way to add support for the touch event depending on the platform.

### PR DESCRIPTION
**Pull request by rexxara**

### CODE REVIEW

**Comment by nikku** [comment]
Thanks for opening this PR.

It will still take a little bit of time to work through our backlog, including this one.

**Comment by philippfromme** [comment]
@rexxara How did you test it? Doesn't work for me.

**Comment by rexxara** [comment]
@philippfromme  What is your device,ios or Android, 
Provide the webview version or safari version.
I tested on my phone and it works. But not test in other device.

**Comment by philippfromme** [comment]
There's no need to detect mobile devices. The issue is touch events, not devices. The reason it wasn't working on my Windows 10 machine (that has a touchscreen) is that it's not a mobile device but still supports touch. I removed the respective code.

I also introduced [`hammerjs`](https://hammerjs.github.io/) as a peer dependency as it's already used by [diagram-js](https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/touch/TouchInteractionEvents.js). Tapping and panning are now working.

I decided against making pinch work after testing it. The minimap is too small for pinching to be useful. Baseides, you can easily zoom by pinching on the canvas.

Thank you for your contribution! 👍🏻

**Pull request closed without merging**
