### PR TITLE
fix(minimap): do not log graphics not found

### LINKED ISSUE #38: "gfx not found" when creating multiple elements at the same time
The message "gfx not found" is always logged when I create a SubProcess with a StartEvent inside. The Start Event is not added yet to the Element Registry when the minimap tries to render it.

### PR DESCRIPTION
**Pull request by philippfromme**
* children might not have been added to the diagram yet
* refactor tests

Closes #38

### CODE REVIEW

**Comment by barmac** [comment]
Unfortunately, this creates a new bug related to a nested children. Please notice how elements disappear from the minimap when the subprocess is moved.

brokennnnn

**Comment by barmac** [comment]
I couldn't reproduce it with Camunda Modeler 3.3.4

**Comment by philippfromme** [comment]
Ah, I see. Alright, I'll fix it.

**Comment by philippfromme** [comment]
@barmac Ready for review round 2!

**Pull request merged**
